services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    # removed this to allow for load balancing scaling with nginx
    # ports:
    #   - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - DB_SERVER=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_DATABASE}?authSource=admin
      - HOST_ADDRESS=${HOST_ADDRESS}
      - SUPER_SECRET=${SUPER_SECRET}
      - GCP_BUCKET_NAME=${GCP_BUCKET_NAME}
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/src/app/gcp-key.json
    volumes:
      - ./gcp-key.json:/usr/src/app/gcp-key.json:ro
      # NOTE: left for use with local storage on server
      # - ./backend/images:/usr/src/app/images
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
